version: '1'
services:
  myapp:
    build:
      context: .
      dockerfile: Dockerfile  # Assuming your Dockerfile is named "Dockerfile"
      tags: ["ultimate-a:ic-1.0"]
    ports:
      - "8080:8080"
